---
- name: Create cronjob with ansible
  hosts: myservers

  tasks:
    - name: Creating a cronjob
      cron:
        name: "Testing Cronjob"
        job: "echo $(date) >> /ansible_cron_tab.txt"

    - name: verify the crontab is created
      shell: crontab -l
      register: cron_output

    - name: print out the verification of crontab
      debug:
        msg: "{{cron_output}}"

